trigger:
  branches:
    include:
      - master

pool:
  name: 'agentPool1' 

variables:
  buildConfiguration: 'Release'
  nodeVersion: '14.x'  

steps:
- task: UseNode@2
  inputs:
    versionSpec: $(nodeVersion)
  displayName: 'Use Node.js $(nodeVersion)'

- script: |
    npm install
  displayName: 'Install Dependencies'

- script: |
    npm run build
  displayName: 'Build Next.js Application'